site_name: napari-labeller
site_description: A plugindoing manual instance segmentation.
site_author: Ian Hunt-Isaak, John Russell

theme: readthedocs


repo_url: https://github.com/Hekstra-Lab/napari-labeller

pages:
- Home: index.md
